spring:
  application:
    name: cloud-provider-movie
    
server:
  port: 8000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/      


  instance:
    ip-address: 192.168.75.1
    prefer-ip-address: true


































